server:
  port: 8901

rest:
  auth-open: true #如果为true,则开启JWT验证

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: mySecret        #jwt秘钥
  expiration: 604800      #7天 单位:秒
  md5-key: randomKey      #md5加密混淆key

mybatis-plus:
  mapper-locations: classpath*:com/enjoy/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/next_film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    filters: log4j,wall,mergeStat


logging:  
  level.root: info
  level.com.enjoy: debug
  path: logs/
  file: next-film.log
